services:
  gielcp:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./config:/app/config
    # networks:
    #   - papamakhtar

# networks:
#   papamakhtar:
#     name: papamakhtar
#     external: true